### ISSUE TITLE
create React/SVG starter project

### ISSUE THREAD

**Issue by fuchsnj** [openathena/web-client#1]

**Comment by a-type** [comment]
Finished boilerplate, but websocket can't connect to the server.

```
Accepted a new tcp connection from 127.0.0.1:53097.
New Connection established
Error: WS Error <Protocol>: Unable to parse WebSocket key.
```

**Comment by brix4dayz** [comment]
Raw events page is working with e72837e

Can POST to `/teams` and the `TEAM_CREATED` event is rendered to the page. If the page is refreshed, `HISTORY` events are immediately sent for each previous `TEAM_CREATED` event.
